version: '3'
services:
  nodejs-app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - my-network
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    networks:
      - my-network
networks:
  my-network:
