version: '3'
services:
  nodejs-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - my-network
  mongodb:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo"
      MONGO_INITDB_ROOT_PASSWORD: "e3-C2EH4Bca-fGEfHdde4a1-DGfBFbH2"
    ports:
      - "27017:27017"
    networks:
      - my-network
networks:
  my-network:
